Num py ek python library hai 
jo math or scitific colobration easily learn krta hai
ye mostly array ke sath kaam karti hai

In [75]:
import numpy as np

In [76]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.array([8,7,6,5,4,3,2,1])
print(a)
print(b)


[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


In [77]:
type(a)

numpy.ndarray

In [78]:
print(a + b)
print(a - b)
print(a * b)

[9 9 9 9 9 9 9 9]
[-7 -5 -3 -1  1  3  5  7]
[ 8 14 18 20 20 18 14  8]


In [79]:
# crate a 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [80]:
# creating a 3D array
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
print(a2.shape)# ye line batati hai array a2 ka shape yaani rows and columns

(2, 3)


In [82]:
print(a2.ndim) # ye line batati hai array a2 ki dimensions yani 2D hai ya 3D


2


In [83]:
print(a2.dtype) # ye line batati hai array a2 ka data type yani integer, float, etc.

int64


In [84]:
np.arange(10)# ye line 0 se lekar 9 tak ke numbers ka array banati hai

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.arange(2,21)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [86]:
np.arange(2,21,2) # ye line 2 se lekar 20 tak ke even numbers ka array banati hai

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [87]:
np.random.randint(1,11, size = (2,3))# ye line 1 se lekar 10 tak ke random integers ka 2x3 ka array banati hai

array([[4, 4, 7],
       [4, 2, 7]], dtype=int32)

In [88]:
x3= np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(x3)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [95]:
print(x3.shape)

(1, 4, 2)


In [90]:
print(x3.dtype)

int64


In [91]:
print(x3.ndim)

3


In [102]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(x)

y = np.array([[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

print(y)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [103]:
print(x * y)

[[[ 13  28  45]
  [ 64  85 108]
  [133 160 189]
  [220 253 288]]]


In [104]:
print(x.shape)# ye line x aur y arrays ka dot product calculate karti hai

(1, 4, 3)


In [105]:
print(y.shape)

(1, 4, 3)


In [110]:
print(a@b) #

120


In [108]:
np.inner(x,y) # ye line x aur y arrays ka dot product calculate karti hai

array([[[[ 86, 104, 122, 140]],

        [[212, 257, 302, 347]],

        [[338, 410, 482, 554]],

        [[464, 563, 662, 761]]]])